#!/usr/bin/env python3
"""Build the clothing store's GTA Online data files from root-cause's public dumps.

  names  -> client_packages/ui/clothing/names.js   (GTA Online item names per drawable/texture, for the shop UI)
  torsos -> packages/clothing/data/besttorso.json  (matching arms/torso per top, so sleeves don't clip)

Sources (extracted from the game's shop metadata):
  https://github.com/root-cause/v-clothingnames
  https://github.com/root-cause/v-besttorso

Re-run after a GTA/DLC update:  python3 tools/gen-clothing-data.py
"""
import json
import os
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NAMES_URL = 'https://raw.githubusercontent.com/root-cause/v-clothingnames/master/{}.json'
TORSO_URL = 'https://raw.githubusercontent.com/root-cause/v-besttorso/master/besttorso_{}.json'

# Our clothing category key -> source file pattern ({} = male/female). Must match CATEGORIES in
# packages/clothing/index.js. Bags (5) and decals (10) have no name dump; they show as "#N".
NAME_FILES = {
    'top': '{}_tops', 'undershirt': '{}_undershirts', 'pants': '{}_legs', 'shoes': '{}_shoes',
    'mask': 'masks_{}', 'neck': '{}_accessories',
    'hat': 'props_{}_hats', 'glasses': 'props_{}_glasses', 'ears': 'props_{}_ears',
    'watch': 'props_{}_watches', 'bracelet': 'props_{}_bracelets',
}


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.loads(response.read().decode('utf-8'))


def build_names():
    """{ m|f: { cat: { drawable: [name | 0 per texture] } } } — 0 = no GTA Online label."""
    out = {}
    for gender in ('male', 'female'):
        by_cat = {}
        for cat, pattern in NAME_FILES.items():
            source = fetch(NAMES_URL.format(pattern.format(gender)))
            cat_names = {}
            for drawable, textures in source.items():
                if int(drawable) < 0:
                    continue
                names = []
                for texture in sorted(textures, key=int):
                    label = textures[texture].get('Localized')
                    names.append(label if label and label != 'NULL' else 0)
                while names and names[-1] == 0:
                    names.pop()
                if names:
                    cat_names[drawable] = names
            by_cat[cat] = cat_names
        out[gender[0]] = by_cat
    return out


def build_torsos():
    """{ m|f: { top: [torsoD, torsoT] | [[torsoD, torsoT] | 0 per texture] } } — tops without data are left out."""
    out = {}
    for gender in ('male', 'female'):
        source = fetch(TORSO_URL.format(gender))
        tops = {}
        for drawable, textures in source.items():
            per_texture = []
            for texture in sorted(textures, key=int):
                entry = textures[texture]
                d, t = entry.get('BestTorsoDrawable', -1), entry.get('BestTorsoTexture', -1)
                per_texture.append([d, max(0, t)] if d is not None and d >= 0 else 0)
            known = [p for p in per_texture if p]
            if not known:
                continue
            unique = {tuple(p) for p in known}
            # Same torso for every texture (almost all tops): store it once.
            tops[drawable] = known[0] if len(unique) == 1 else per_texture
        out[gender[0]] = tops
    return out


def main():
    names = build_names()
    names_path = os.path.join(ROOT, 'client_packages', 'ui', 'clothing', 'names.js')
    with open(names_path, 'w', encoding='utf-8') as handle:
        handle.write('// Generated by tools/gen-clothing-data.py from root-cause/v-clothingnames — do not edit.\n')
        handle.write('window.CLOTH_NAMES = ')
        json.dump(names, handle, ensure_ascii=False, separators=(',', ':'))
        handle.write(';\n')

    torsos = build_torsos()
    torso_dir = os.path.join(ROOT, 'packages', 'clothing', 'data')
    os.makedirs(torso_dir, exist_ok=True)
    with open(os.path.join(torso_dir, 'besttorso.json'), 'w', encoding='utf-8') as handle:
        json.dump(torsos, handle, separators=(',', ':'))

    for gender in ('m', 'f'):
        print(gender, 'names:', {cat: len(v) for cat, v in names[gender].items()}, '| tops with torso:', len(torsos[gender]))


if __name__ == '__main__':
    main()
