#!/usr/bin/env python3
"""Build the tattoo salon's data from DurtyFree's GTA V data dump (pedOverlayCollections.json).

  -> packages/tattoo/data.json               (server: validates ids, resolves hashes)
  -> client_packages/ui/tattoo/data.js       (salon page: the lists it browses)

Every TYPE_TATTOO overlay is included (crew badges are not tattoos). Per gender, items are ordered by
zone then collection then name; item = [zone, collection, overlayHash, name, facing]; an item's id is its index in that gender's list, so re-running after a
game update can shift ids — saved tattoos store ids, so only regenerate with that in mind.
"""
import json
import os
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URL = 'https://raw.githubusercontent.com/DurtyFree/gta-v-data-dumps/master/pedOverlayCollections.json'
ZONES = ['ZONE_HEAD', 'ZONE_TORSO', 'ZONE_LEFT_ARM', 'ZONE_RIGHT_ARM', 'ZONE_LEFT_LEG', 'ZONE_RIGHT_LEG']

with urllib.request.urlopen(URL, timeout=60) as response:
    dump = json.loads(response.read().decode('utf-8'))

# Side of the body a tattoo is drawn on (the dump's Facing): 0 unknown, 1 front, 2 back, 3 side.
FACING = {'TATTOO_FRONT': 1, 'TATTOO_CHEST': 1, 'TATTOO_FRONT_LEFT': 1, 'TATTOO_FRONT_RIGHT': 1, 'TATTOO_STOMACH': 1,
          'TATTOO_BACK': 2, 'TATTOO_LEFT': 3, 'TATTOO_RIGHT': 3}

collections, items = [], {'m': [], 'f': []}
for collection in dump:
    tattoos = [o for o in collection['Overlays'] if o['Type'] == 'TYPE_TATTOO' and o['ZoneName'] in ZONES]
    if not tattoos:
        continue
    index = len(collections)
    label = collection['CollectionName'].replace('_overlays', '')
    label = label[2:] if label.startswith('mp') and len(label) > 2 else label
    collections.append({'n': label, 'h': collection['CollectionHash']})
    for o in tattoos:
        for gender, wanted in (('m', 'GENDER_MALE'), ('f', 'GENDER_FEMALE')):
            if o['Gender'] in (wanted, 'GENDER_DONTCARE'):
                items[gender].append([ZONES.index(o['ZoneName']), index, o['OverlayHash'], o['OverlayName'], FACING.get(o.get('Facing'), 0)])
for gender in items:
    items[gender].sort(key=lambda it: (it[0], it[1], it[3].lower()))

data = {'collections': collections, 'm': items['m'], 'f': items['f']}
with open(os.path.join(ROOT, 'packages', 'tattoo', 'data.json'), 'w') as handle:
    json.dump(data, handle, separators=(',', ':'))
with open(os.path.join(ROOT, 'client_packages', 'ui', 'tattoo', 'data.js'), 'w') as handle:
    handle.write('// Generated by tools/gen-tattoo-data.py — do not edit.\nwindow.TATTOOS = ' + json.dumps(data, separators=(',', ':')) + ';\n')
print({g: len(items[g]) for g in items}, len(collections), 'collections')
